
server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/20_mall2?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 123456
