server:
  port: 8083
#mybatisd的配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/20_mall2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  resources:
    static-locations: file:D:/WangDao/Project2/project2/src/main/resources/static/pic/
  mvc:
    static-path-pattern: /wx/storage/fetch/**

mybatis:
  type-handlers-package: com.lxlt.typehandler

map:
  domain: 'http://localhost:'
  port: ${server.port}
  uploadFileDirectory: /src/main/resources/static/pic/
  staticPath: /wx/storage/fetch/

logging:
  level:
    com.lxlt.mapper: debug

