server:
  port: 8083
#mybatisd的配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/20_mall2
    username: root
    password: 123456
  resources:
    static-locations: file:D:/WangDao/Project2/project2${map.uploadFileDirectory}
  mvc:
    static-path-pattern: /wx/storage/fetch/**
map:
  domain: 'http://localhost:'
  port: ${server.port}
  uploadFileDirectory: /src/main/resources/static/pic/
  staticPath: ${spring.mvc.static-path-pattern}
